name: Build, Pack and Publish

on:
  push:
    branches: [ "main" ] 

env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
  NODE_VERSION: 19

jobs:
  build-and-test:

    name: build-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      working-directory: src
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src

  release:
    needs: build-and-test
    name: release-latest
    runs-on: ubuntu-latest

    steps:
    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm install
      working-directory: ./
    - name: Release
      run: npx semantic-release
      working-directory: ./
